// All 84 public videos and 24 Shorts from @f.ifilmwed, checked 2026-10-06.
window.weddingVideos = [
  ['6Ttg6KKf6qs','꽃으로 가득했던 봄날의 야외웨딩｜프라움 웨딩필름 Wedding Film','1:00'],
  ['5uGQLJWCCds','강변의 풍경 속, 영화처럼 펼쳐진 프라움 야외웨딩｜Wedding Film','1:00'],
  ['9sExhjYjmUw','[에프아이필름] 더링크 호텔 The link Seoul | 본식DVD, 웨딩영상, wedding film','2:01'],
  ['9N3eqMJYWTQ','[에프아이필름] 솔스퀘어컨벤션 solconvention | 본식DVD, 웨딩영상, wedding film 4K','2:02'],
  ['3c7dAJEaU_8','[에프아이필름] 엘리에나 호텔 Eliena Hotel Wedding | 본식DVD, 웨딩영상, wedding film','2:01'],
  ['3TAjXHnUMu4','[에프아이필름] 엠베서더 풀만 서울 The ambassador seoul | 본식DVD, 웨딩영상, wedding film','2:01'],
  ['ueALj5Q9Mis','[에프아이필름] 서초 더 화이트베일 the white veil | 본식DVD, 웨딩영상, wedding film','2:09'],
  ['6B6aInfxxaM','[에프아이필름] 서울대연구공원 SNU Wedding Hall | 본식DVD, 웨딩영상, wedding film','2:19'],
  ['sX0rtrjQtTk','[에프아이필름] 그랜드 하얏트 Grand Hyatt Seoul | 본식DVD, 웨딩영상, wedding film','2:39'],
  ['pgXWwQK5uDY','[에프아이필름] 파주 퍼스트가든 FIRST GARDEN WEDDING | 본식DVD, 웨딩영상, wedding film','2:13'],
  ['9zs0F_Z0Jbs','[에프아이필름] 노블발렌티 대치 Noblevalenti_daechi | 본식DVD, 웨딩영상, Wedding film','2:09'],
  ['d_CJzHII6cI','[에프아이필름] 의정부더레이나 THE REINA | 본식DVD, 웨딩영상, Wedding film','2:02'],
  ['umFcOYaIzNE','소노펠리체컨벤션 SONO FELICE WEDDING&CONVENTION','2:13'],
  ['oS-4LH9Z6_k','보타닉파크 Botanic Park Wedding','1:51'],
  ['bVG1DzF8lvw','더채플엣청담 The Chapel at Cheongdam','2:02'],
  ['qzmodaWpN5M','고려교우회관 Korea University','1:43'],
  ['C4zYp_mpuys','더화이트베일 The White Veil','2:06'],
  ['9ZoDmbk8IUY','서울대연구공원 SNU WEDDING HALL','2:04'],
  ['6vGwMY_dbrw','라비두스 LAVIEDOUCE','2:17'],
  ['X_AqycaVoTM','더채플앳청담 The Chapel at Cheongdam','1:34'],
  ['b8zjgRhIkRk','로얄파크 RoyalPark · 4K UHD wedding film','0:35'],
  ['05JjBSWm-18','JW 메리어트 JW marriott','1:57'],
  ['9am-QBsPCaA','그레이스파티 GRACE PARTY','2:04'],
  ['2a8NJsEOwIU','더컨벤션 THE CONVENTION','1:34'],
  ['I0MhTKqwBnw','로얄파크 RoyalPark','1:52'],
  ['65AyOLoXTuU','노블발렌티삼성 Noblevalenti','1:31'],
  ['4M9jKKHiQ8Y','켄싱턴호텔 쇼케이스 Kensington Hotel Showcase','1:01'],
  ['zn1sFwMxRAk','더채플앳청담 The Chapel at Cheongdam','1:28'],
  ['ps8YYKcz6CA','더화이트베일 The White Veil','1:33'],
  ['v-g8Whhvv5o','플라자 호텔 Hotel Plaza','1:33'],
  ['bnFvhNaGdww','더리버사이드호텔 THE RIVERSIDE HOTEL','1:00'],
  ['T5mfm_vSJWk','이천아모르 AMOR','1:24'],
  ['412WY0cnzg8','한국의 집 KOREA HOUSE','1:14'],
  ['SvYQhF3CNWg','이룸웨딩 Iruum convention','1:08'],
  ['uDDGdhfupWg','인천 아시아드 Asiad Wedding Convention','1:28'],
  ['LRWSQPf1qvQ','플라자 호텔 HOTEL PLAZA','1:06'],
  ['gRmaZ1PpMVs','더채플앳청담 The Chapel at Cheongdam','1:00'],
  ['_cm87F5f6IU','캘리포니아 레이크타호 LAKETAHOE · 홍보영상','1:28'],
  ['7xWVLHLjX64','캘리포니아 요세미티 Yosemite National Park · 홍보영상','1:34'],
  ['QgfZ_aspLw8','두가헌 DUGAHUN','2:12'],
  ['F8Rlih7zZTc','마리나파크 Marina Park','1:01'],
  ['w07B_EeKX6M','의왕 뜰안채2 ddlanche','0:58'],
  ['mLb7Z8DEPe8','부천MJ컨벤션 MJ CONVENTION','1:00'],
  ['iEcK_XQNgS8','더컨벤션 신사 THE CONVENTION','1:26'],
  ['i0ZNcMuG9t4','서울대 이라운지 E.LOUNGE','1:31'],
  ['KO2ILAFp1Tg','aT포레 ATFORET','1:01'],
  ['luQbR_k5JI4','천안 비렌티 VIRENTI','1:01'],
  ['w4ji8-jcqW0','더화이트베일 THEWHITEVEIL','1:00'],
  ['GEb_Kku8i7k','리움 하우스 LIUMHOUSE','0:56'],
  ['1VNoHz2va3I','더라빌 THELAVILLE','0:59'],
  ['KyBs3cbCA-s','의왕뜰안채2 DDEULANCHE2','0:58'],
  ['Vn7sB_SVbEU','마리나파크 MARINA PARK','1:01'],
  ['g8_JYZruh4I','육사화랑정원 Military Art Gallery','1:01'],
  ['VKETXhZmDfs','웨딩시그니처 Signature','1:16'],
  ['vuwnNNH2RaQ','빌라드지디 청담 VILLA DE GD CHUNGDAM','0:47'],
  ['zkKHaugAclQ','빌라드지디 청담 VILLA DE GD CHUNGDAM','0:55'],
  ['HYq3Q-8-eWM','아이오유레스토랑 IOU Restaurant','1:01'],
  ['div3-UbOfho','베뉴지 Venueg','1:25'],
  ['f1GFliOr6QI','더발렌티청담 THE Valenti CHEONGDAM','1:05'],
  ['Gk3dXVwlhuM','더채플앳청담 THE Chapel at CHEONGDAM','1:00'],
  ['y35MsUBLrLs','보타닉파크 Botanic Park Wedding','1:00'],
  ['dLSVbtuxojE','토브헤세드 TOV HESED','1:00'],
  ['DRVTI0ppEc0','소공동 롯데호텔 Lotte Hotel Seoul','1:00'],
  ['d6MkSV-wUw8','그랜드힐 GrandHill','1:01'],
  ['iHba7R_MpSw','파티오나인 Patio9','1:01'],
  ['9-p5Pkz9Kk0','라플레이스 La Place','1:01'],
  ['-mJQqJy37I8','두가헌 Dugahun','2:12'],
  ['KPjrma-tNj4','서울웨딩타워 Seoul Wedding Tower','1:26'],
  ['-tcdyUdJiH8','MW컨벤션 MW Convention','1:00'],
  ['lXZ3aoWI8Pk','그랜드인터컨티넨탈 Grand InterContinental','1:01'],
  ['YLy2cFDWatk','엘블레스 Elbless','1:01'],
  ['eTY_MZBZNyg','남산예술원 NAMSANART WEDDINGHALL','3:08'],
  ['fzYzl_werto','빌라드지디 수서 VILLA DE GD SUSEO','1:01'],
  ['NKwn603Za6E','더채플앳웨스트 The CHAPEL AT WEST','1:01'],
  ['hzOXoVLXMo4','신도림라마다 SINDORIM RAMADA','0:59'],
  ['d44MVtsYkkU','프라움 PRAUM','1:00'],
  ['NF9InoDlNpo','수원 이비스앰배서더 SUWON IBIS AMBASSADOR','1:12'],
  ['GUPtFAxOLe0','상록아트홀 SANGROK ARTHALL','1:10'],
  ['fVOpNuS3UPc','여의도웨딩컨벤션 YEOUIDO WeddingHall','1:06'],
  ['Vh-VuvoY5uQ','식스플로어 SIXTH FLOOR STUDIO · 웨딩스튜디오 영상','1:00'],
  ['HJacaUvUs4s','보테가마지오 BOTTEGAMAGGIO','1:01'],
  ['cjEY-gjEmJg','누아주스튜디오 NUAGE STUDIO · 웨딩스튜디오 영상','1:00'],
  ['5sU3lLN8tKA','송도 메리빌리아 MARRYVILIA IN SONGDO','1:01'],
  ['gJzg23pDXrc','더채플앳논현 라포레홀 The CHAPEL AT NONHYEON','1:14']
].map(([videoId,title,duration],index) => ({
  videoId,title,duration,id:`WD${String(index+1).padStart(2,'0')}`,
  category:'wedding',label:'WEDDING FILM',alt:title,source:'에프아이필름 WED',visibility:'public'
}));
window.weddingVideos.push(...[
  ['GgpgSv0bEeM','햇살까지 축복해준 어느 날의 결혼식'],
  ['aDgqiCLHtQU',"낭만적인 야외예식 '프라움' 드론 촬영"],
  ['gkcQe9ihSUc','다시보는 신부님 친구분들 인터뷰 full 버전'],
  ['WRnORER0htI',"넓은 층고와 웅장함을 느낄 수 있는 '더채플앳청담'"],
  ['g7mlQpSxShg','사랑이 가득 담긴 인터뷰'],
  ['qnF-QhL1uvs','신랑 신부님의 즐거운 댄스타임'],
  ['wUVuKG13-5k','사랑과 행복을 가득 담아'],
  ['Ibcd-nLWcAg','하객들의 반응이 가장 뜨거웠던 퇴장 댄스'],
  ['cnkIcAfhuNk','너무 상큼한 신랑신부님의 댄스 타임'],
  ['12bQfInnZUw','영원히 잊지 못할 순간'],
  ['EhRp8gj8LeQ','결혼 축하해~ 행복하게 잘 살아'],
  ['S1sX_pR2_88','상큼한 신부님과 멋진 신랑님'],
  ['hf9ZFTXazmY','사랑이 가득 담긴 양가 부모님의 인터뷰'],
  ['oMFgJG1Hig8','모든 순간을 영화처럼 담아드려요'],
  ['YBVCQxCo6AE','친구들의 따뜻한 축하 메시지'],
  ['rSZ_iWwqKkU',"봄을 알리는 따스한 야외 예식 '프라움'"],
  ['muiQ1q-rE_0',"우아하고 성스러운 채플 웨딩 '더채플앳청담' 예식"],
  ['Lry3Rm0GO2U','화려하고 풍성하고 아름다운 로얄파크 예식'],
  ['qaCbDRHMyLY',"봄이 다가오는듯한 도심속의 가든컨셉 웨딩홀 '로얄파크'"],
  ['sIb9uls0mLo','다나카상의 감미로운 축가무대'],
  ['8JKTGyPVpe8','천만 유튜버 쏘영님의 웨딩스튜디오 촬영'],
  ['xgZGFG2mmHw','더채플앳청담 The Chapel'],
  ['hlyBzdw02xE','더화이트베일 The White Veil'],
  ['sv0gUCR0oyE','로얄파크 Royal Park']
].map(([videoId,title],index) => ({
  videoId,title,duration:'SHORTS',id:`WS${String(index+1).padStart(2,'0')}`,
  category:'wedding',label:'WEDDING SHORTS',alt:title,source:'에프아이필름 WED',visibility:'public',kind:'short'
})));
